package com.tujuhsembilan.bookrecipe.model;
// Generated Jan 4, 2024, 3:00:37 PM by Hibernate Tools 6.3.1.Final

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.sql.Timestamp;
import java.util.Set;

/**
 * Recipes generated by hbm2java
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@EntityListeners(AuditingEntityListener.class)
public class Recipes implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1873449508321388125L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_recipes_recipe_id_seq")
    @SequenceGenerator(name="generator_recipes_recipe_id_seq", sequenceName="recipes_recipe_id_seq", schema = "public", allocationSize = 1)
    @Column(name = "recipe_id", unique = true, nullable = false)
    private int recipeId;

    @ManyToOne
    @JoinColumn(name = "category_id")
    private Categories categories;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private Users users;

    @ManyToOne
    @JoinColumn(name = "level_id")
    private Levels levels;

    @Column(name = "recipe_name")
    private String recipeName;

    @Column(name = "image_filename")
    private String imageFilename;

    @Column(name = "time_cook")
    private Integer timeCook;

    @Column(name = "ingredient")
    private String ingredient;

    @Column(name = "how_to_cook")
    private String howToCook;

    @Column(name = "is_deleted")
    private Boolean isDeleted;

    @Column(name = "created_by")
    private String createdBy;

    @CreatedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 29)
    private Timestamp createdTime;

    @Column(name = "modified_by")
    private String modifiedBy;

    @LastModifiedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modified_time", length = 29)
    private Timestamp modifiedTime;

    @OneToMany(mappedBy = "recipes")
    private Set<FavoriteFoods> favoriteFoodses;

}
