package com.tujuhsembilan.bookrecipe.model;
// Generated Jan 4, 2024, 3:00:37 PM by Hibernate Tools 6.3.1.Final

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.sql.Timestamp;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Builder
@EntityListeners(AuditingEntityListener.class)
public class Users implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5894679636266655135L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator_users_user_id_seq")
    @SequenceGenerator(name="generator_users_user_id_seq", sequenceName="users_user_id_seq", schema = "public", allocationSize = 1)
    @Column(name = "user_id", unique = true, nullable = false)
    private int userId;

    @Column(name = "username")
    private String username;

    @Column(name = "fullname")
    private String fullname;

    @Column(name = "password")
    private String password;

    @Column(name = "role")
    private String role;

    @Column(name = "is_deleted")
    private Boolean isDeleted;

    @Column(name = "created_by")
    private String createdBy;

    @CreatedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_time", length = 29)
    private Timestamp createdTime;

    @Column(name = "modified_by")
    private String modifiedBy;

    @LastModifiedDate
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "modified_time", length = 29)
    private Timestamp modifiedTime;

    @OneToMany(mappedBy = "users")
    private Set<Recipes> recipeses;

    @OneToMany(mappedBy = "users")
    private Set<FavoriteFoods> favoriteFoodses;
}
